-- MySQL Script generated by MySQL Workbench
-- Tue May 21 11:02:05 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`korisnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`korisnik` (
  `ID_korisnik` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `ime` VARCHAR(45) NOT NULL,
  `prezime` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `admin` TINYINT NOT NULL,
  PRIMARY KEY (`ID_korisnik`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`kategorija`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`kategorija` (
  `ID_kategorija` INT NOT NULL,
  `naziv` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ID_kategorija`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`proizvod`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proizvod` (
  `ID_proizvod` INT NOT NULL,
  `naziv` VARCHAR(45) NOT NULL,
  `slika` VARCHAR(100) NOT NULL,
  `cijena` DECIMAL(7,2) NOT NULL,
  `datum_objavljivanja` DATE NOT NULL,
  `opis` MEDIUMTEXT NOT NULL,
  `aktivan` TINYINT NOT NULL,
  `akcija` TINYINT NOT NULL,
  `kategorija_ID_kategorija` INT NOT NULL,
  `korisnik_ID_korisnik` INT NOT NULL,
  PRIMARY KEY (`ID_proizvod`),
  INDEX `fk_proizvod_kategorija_idx` (`kategorija_ID_kategorija` ASC),
  INDEX `fk_proizvod_korisnik1_idx` (`korisnik_ID_korisnik` ASC),
  CONSTRAINT `fk_proizvod_kategorija`
    FOREIGN KEY (`kategorija_ID_kategorija`)
    REFERENCES `mydb`.`kategorija` (`ID_kategorija`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proizvod_korisnik1`
    FOREIGN KEY (`korisnik_ID_korisnik`)
    REFERENCES `mydb`.`korisnik` (`ID_korisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);


-- -----------------------------------------------------
-- Table `mydb`.`adresa_korisnika`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`adresa_korisnika` (
  `ID_adresa` INT NOT NULL,
  `ulica_i_broj` VARCHAR(15) NOT NULL,
  `postanski_br` VARCHAR(45) NOT NULL,
  `grad` VARCHAR(45) NOT NULL,
  `drzava` VARCHAR(45) NOT NULL,
  `korisnik_ID_korisnik` INT NOT NULL,
  PRIMARY KEY (`ID_adresa`),
  INDEX `fk_adresa_korisnika_korisnik1_idx` (`korisnik_ID_korisnik` ASC),
  CONSTRAINT `fk_adresa_korisnika_korisnik1`
    FOREIGN KEY (`korisnik_ID_korisnik`)
    REFERENCES `mydb`.`korisnik` (`ID_korisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`narudzba`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`narudzba` (
  `ID_narudzba` INT NOT NULL,
  `datum_narudzbe` DATE NOT NULL,
  `sveukupna_cijena` DECIMAL(7,2) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `korisnik_ID_korisnik` INT NOT NULL,
  `adresa_korisnika_ID_adresa` INT NOT NULL,
  PRIMARY KEY (`ID_narudzba`),
  INDEX `fk_narudzba_korisnik1_idx` (`korisnik_ID_korisnik` ASC),
  INDEX `fk_narudzba_adresa_korisnika1_idx` (`adresa_korisnika_ID_adresa` ASC),
  CONSTRAINT `fk_narudzba_korisnik1`
    FOREIGN KEY (`korisnik_ID_korisnik`)
    REFERENCES `mydb`.`korisnik` (`ID_korisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_narudzba_adresa_korisnika1`
    FOREIGN KEY (`adresa_korisnika_ID_adresa`)
    REFERENCES `mydb`.`adresa_korisnika` (`ID_adresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`narudzba_proizvod`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`narudzba_proizvod` (
  `narudzba_proizvod` VARCHAR(45) NOT NULL,
  `ukupna_cijena_stavke` DECIMAL(7,2) NOT NULL,
  `narudzba_ID_narudzba` INT NOT NULL,
  `proizvod_ID_proizvod` INT NOT NULL,
  INDEX `fk_narudzba_proizvod_narudzba1_idx` (`narudzba_ID_narudzba` ASC),
  INDEX `fk_narudzba_proizvod_proizvod1_idx` (`proizvod_ID_proizvod` ASC),
  CONSTRAINT `fk_narudzba_proizvod_narudzba1`
    FOREIGN KEY (`narudzba_ID_narudzba`)
    REFERENCES `mydb`.`narudzba` (`ID_narudzba`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_narudzba_proizvod_proizvod1`
    FOREIGN KEY (`proizvod_ID_proizvod`)
    REFERENCES `mydb`.`proizvod` (`ID_proizvod`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
